# Generated by Django 4.0.4 on 2022-05-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_megazinepages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='megazinecategories',
            old_name='CategoryID',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='megazinedetails',
            old_name='CategoryID',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='megazinedetails',
            old_name='MegazineID',
            new_name='Megazines',
        ),
        migrations.RenameField(
            model_name='megazinepages',
            old_name='MegazineID',
            new_name='Megazines',
        ),
    ]
