# Generated by Django 4.0.4 on 2022-05-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_categoryid_megazinecategories_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='megazinecategories',
            old_name='Categories',
            new_name='CategoryID',
        ),
        migrations.RenameField(
            model_name='megazinedetails',
            old_name='Megazines',
            new_name='MegazineID',
        ),
    ]
